[package]
name = "tsak"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "3.2.16", features = ["derive"] }
env_logger = "0.9.0"
hostname = "^0.3"
lexical-core = "0.8.5"
log = "0.4.17"
neofiglet = "0.1.1"
rhai = "1.10.1"
rhai-rand = "0.1.4"
rhai-sci = "0.1.7"
rustyline = "10.0.0"

[dependencies.uuid]
version = "1.1.2"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]
